[global]
   server string = NAS
   server role = standalone server
   log file = /dev/stdout
   max log size = 50
   dns proxy = no
   map to guest = Bad User
   server min protocol = SMB2

[media]
   path = /media
   browseable = yes
   read only = no
   guest ok = no
   valid users = augusto
   force user = augusto

[data]
   path = /data
   browseable = yes
   read only = no
   guest ok = no
   valid users = augusto
   force user = augusto

[downloads]
   path = /downloads
   browseable = yes
   read only = no
   guest ok = no
   valid users = augusto
   force user = augusto

[backup]
   path = /backup
   browseable = yes
   read only = no
   guest ok = no
   valid users = augusto
   force user = augusto
